name: app-with-job
region: nyc

# 1. Web Service Component
services:
  - name: app-with-job         # Component 1 (Web Service)
    github:
      repo: Ajaykumar250/app_with_joob
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: node-js
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production

# 2. Separate Job Component
jobs:
  - name: database-migration-job # Component 2 (Job)
    kind: PRE_DEPLOY             # PRE_DEPLOY makes it run before the web service updates
    github:
      repo: Ajaykumar250/app_with_joob
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: node-js
    run_command: npm run migrate
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
