name: app-with-predeploy-job
region: nyc
services:
  - name: web-service
    github:
      repo: Ajaykumar250/app_with_joob
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: node-js
    run_command: npm start
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production

jobs:
  - name: predeploy-migration
    kind: PRE_DEPLOY
    github:
      repo: Ajaykumar250/app_with_joob
      branch: main
      deploy_on_push: true
    source_dir: /
    environment_slug: node-js
    run_command: npm run migrate
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
